---
- ansible.builtin.import_tasks: roles/stack/tasks/repository.yml
- ansible.builtin.import_tasks: roles/stack/tasks/memcached.yml
- ansible.builtin.import_tasks: roles/stack/tasks/nginx.yml
- ansible.builtin.import_tasks: roles/stack/tasks/php.yml
- ansible.builtin.import_tasks: roles/stack/tasks/mariadb.yml
