---
# Setup NGINX Stack

- name: Installing NGINX
  ansible.builtin.apt:
    name:
      - nginx
    state: latest
    update_cache: yes
  register: package_install
  # The notify will call the ../handlers/main.yml
  notify: service nginx restart
  tags: nginx

- name: Setup NGINX Files
  ansible.builtin.template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "../templates/nginx/nginx.conf", dest: "/etc/nginx/nginx.conf" }
    - { src: "../templates/nginx/conf.d/realip.conf", dest: "/etc/nginx/conf.d/realip.conf" }
    - { src: "../templates/nginx/conf.d/fastcgi.conf.j2", dest: "/etc/nginx/conf.d/fastcgi.conf" }
  # The notify will call the ../handlers/main.yml
  notify: service nginx reload
  tags: nginx

- name: Setup NGINX Default Config Files
  ansible.builtin.copy:
    src: ../templates/nginx/ansipress/
    dest: /etc/nginx/ansipress/
  notify: service nginx reload
  tags: nginx

# one-time setup of stronger DH pem for nginx ssl forward secrecy (slow)
#- name: Ensure openssl is installed.
#  apt: name=openssl state=latest update_cache=yes

- name: Generate Diffie-Hellman params for strong SSL.
  ansible.builtin.command: "openssl dhparam -out '/etc/ssl/certs/dhparam.pem' 2048"
  args:
    creates: /etc/ssl/certs/dhparam.pem
  tags: nginx

# Default value of net.core.somaxconn, NGINX uses by default 511
- name: Setup net.core.somaxconn and net.core.netdev_max_backlog in /etc/sysctl.conf
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  with_items:
    - { name: "net.core.somaxconn", value: "4096" }
    - { name: "net.core.netdev_max_backlog", value: "65535" }
  tags: nginx, nginx_sysctl

- name: Adjust Default Security Limit Max Open File
  community.general.pam_limits:
    domain: root
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: 65535
  with_items:
    - { limit_type: "soft", limit_item: "nproc" }
    - { limit_type: "hard", limit_item: "nproc" }
    - { limit_type: "soft", limit_item: "nofile" }
    - { limit_type: "hard", limit_item: "nofile" }
  tags: nginx, nginx_sysctl
