---
- name: Adding NGINX Repository, Hold on...
  apt_repository: repo='deb http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_{{ ansible_distribution_version }}/ /' state=present filename=nginx
  register: nginx_repo

- name: Adding NGINX Repository Key, Hold on...
  apt_key: url=http://download.opensuse.org/repositories/home:rtCamp:EasyEngine/xUbuntu_{{ ansible_distribution_version }}/Release.key  state=present
  register: nginx_key

- include: roles/libs/tasks/apt/update.yml
  when: nginx_repo.changed == True or nginx_key.changed == True

- name: Installing NGINX, Hold on...
  apt: name=nginx-custom state=present
  register: package_install
  # The notify will call the ../handlers/main.yml
  notify: service nginx restart
