---
- name: Adding NGINX Repository, Hold on...
  apt_repository: repo=ppa:miteshshah/nginx-pagespeed
  register: nginx_repo

- include: roles/libs/tasks/apt/update.yml
  when: nginx_repo.changed == True or nginx_key.changed == True

- name: Installing NGINX, Hold on...
  apt: name=nginx-pagespeed state=present
  register: package_install
  # The notify will call the ../handlers/main.yml
  notify: service nginx restart
