---
- name: Welcome to AnsiPress Setup
  hosts: AnsiPress

  roles:
    - bootstrap
    - reboot
    - user

  vars_prompt:
    - name:   "username"
      prompt: "Enter username: "
      private: no
    - name:   "password"
      prompt: "Enter password: "
      encrypt: "md5_crypt"
      salt_size: 8
      private: yes
