---
# Log All Commands
- name: Log All Commands - Setup /etc/bash.bashrc
  ansible.builtin.lineinfile:
    state: present
    dest: "/etc/bash.bashrc"
    line: "export PROMPT_COMMAND='RETRN_VAL=$?;logger -p local6.debug \"$(whoami) [$$]: $(history 1 | sed \"s/^[ ]*[0-9]\\+[ ]*//\" ) [$RETRN_VAL]\"'"

- name: Log All Commands - Setup /etc/rsyslog.d/bash.conf
  ansible.builtin.copy:
    dest: "/etc/rsyslog.d/bash.conf"
    content: local6.*    /var/log/commands.log
  notify: service rsyslog restart

- name: Log All Commands - Setup /var/log/commands.log
  ansible.builtin.file:
    path: /var/log/commands.log
    owner: syslog
    group: syslog
    mode: 0640
    state: touch

- name: Log All Commands - Setup logrotate
  ansible.builtin.copy:
    src: "../templates/rsyslog"
    dest: "/etc/logrotate.d/rsyslog"
  notify: service rsyslog restart
