---
# Log All Commands
- name: Log All Commands - Setup /etc/bash.bashrc, Hold on...
  lineinfile:
    state: present
    dest: "/etc/bash.bashrc"
    line: "export PROMPT_COMMAND='RETRN_VAL=$?;logger -p local6.debug \"$(whoami) [$$]: $(history 1 | sed \"s/^[ ]*[0-9]\\+[ ]*//\" ) [$RETRN_VAL]\"'"

- name: Log All Commands - Setup /etc/rsyslog.d/bash.conf, Hold on...
  copy:
    dest: "/etc/rsyslog.d/bash.conf"
    content: local6.*    /var/log/commands.log

- name: Log All Commands - Setup /var/log/commands.log, Hold on...
  file:
    path: /var/log/commands.log
    owner: syslog
    group: syslog
    mode: 0640
    state: touch

- name: Log All Commands - Setup logrotate, Hold on...
  lineinfile:
    dest: "/etc/logrotate.d/rsyslog"
    regexp: "{{ item.regexp }}"
    backrefs: yes
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^/var/log/messages', line: '/var/log/messages\n/var/log/commands.log' }

- name: service rsyslog restart, Hold on...
  service:
    name: rsyslog
    state: restarted
