---
- name: Creating PHP {{ username | lower }} Pool, Hold on...
  copy:
    src: /etc/php/7.1/fpm/pool.d/www.conf
    dest: /etc/php/7.1/fpm/pool.d/{{ username | lower }}.conf
    remote_src: true

- name: Tunning PHP {{ username | lower }} Pool Variables, Hold on...
  lineinfile:
    dest: /etc/php/7.1/fpm/pool.d/{{ username | lower }}.conf
    regexp: "{{ item.regexp }}"
    backrefs: yes
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^\[www\]', line: "[{{ username | lower }}]" }
    - { regexp: '^user = www-data', line: 'user = {{ username | lower }}' }
    - { regexp: '^group = www-data', line: 'group = {{ username | lower }}' }
    - { regexp: '^listen = 127.0.0.1:9000', line: 'listen = 127.0.0.1:{{ php_pool.stdout }};' }
  # The notify will call the ../handlers/main.yml
  notify: service php7.1-fpm reload
