---
- include: roles/site/tasks/mysql.yml

- name: Downloading Latest WordPress, Hold on...
  shell: cd /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/htdocs/ && wpcli --allow-root core download

- name: Fetching random salts for WordPress config, Hold on...
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    method: GET
    return_content: yes
  register: wp_salt

- name: Copy wp-config.php File, Hold on...
  template: src=wordpress/wp-config.php dest=/home/{{ username | lower }}/vhosts/{{ website_name | lower }}/wp-config.php

# Gererate Random Password For WordPress User
- include: roles/libs/tasks/random_password.yml

- name: Setup WordPress Tables, Hold on...
  shell: cd /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/htdocs/ && wpcli core install --allow-root  --url={{ website_name | lower }} --title="{{ website_name | lower }}" --admin_name="{{ username | lower }}" --admin_password={{ random_password.stdout }} --admin_email="{{ username | lower }}@localhost.localdomain"

- name: Setup WordPress Permalink, Hold on...
  shell: cd /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/htdocs/ && wpcli rewrite structure --allow-root /%year%/%monthnum%/%day%/%postname%/

- name: Fixing WordPress Permissions, Hold On
  file:
    path: /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/
    state: directory
    recurse: yes
    owner: "{{ username | lower }}"
    group: "{{ username | lower }}"

- name: Getting WordPress Setup Information, Hold on...
  debug:
    msg: "{{ item }}"
  with_items:
    - WordPress Username = {{ username | lower }}
    - WordPress Password = {{ random_password.stdout }}
