---
- name: Installing Fail2ban, Hold on...
  apt: name={{ item }} state=present
  with_items:
    - fail2ban
  register: package_install
  # The notify will call the ../handlers/main.yml
  notify: service fail2ban restart

- name: Copying Configuration File, Hold on...
  template:
    src: ../templates/jail.local
    dest: /etc/fail2ban/jail.local
  when: package_install.changed == True
