---
# Setup NGINX PlayBook

- name: Adding NGINX Repository, Hold on...
  apt_repository: repo=ppa:miteshshah/nginx-pagespeed
  register: nginx_repo

- include: roles/libs/tasks/apt/update.yml
  when: nginx_repo.changed == True

- name: Installing NGINX, Hold on...
  apt: name=nginx-pagespeed state=present
  register: package_install

- name: Setup AnsiPress NGINX Files, Hold on...
  copy:
    src: ../templates/ansipress
    dest: /etc/nginx/
  when: package_install.changed == True

- name: Setup HTTP AUTH, Hold On...
  htpasswd:
    path: /etc/nginx/htpasswd
    name: AnsiPress
    password: 'AnsiPress'
  when: package_install.changed == True

# In order to allow nginx-helper delete NGINX cache Files
# We need to change chmod -R 777 /var/run/nginx-cache
# As each website has own separate users and that users need permission to
# Remove cached files from this directory
- name: Fix NGINX Cache Didrectory Permission, Hold On
  file:
    path: /var/run/nginx-cache
    state: directory
    recurse: yes
    mode: 0777
  when: package_install.changed == True

# We need PHP Pool Number
# In Order to setup PHP/MySQL/WordPress website template
# We need to replace php_pool variable on those templates
- name: Calculate PHP Pool Value, Hold on...
  include: roles/libs/tasks/php_pool.yml
  when: website_type != "html" and website_type != "HTML"

- name: Check /etc/nginx/sites-available/{{ website_name | lower }}.conf, Hold on...
  stat:
    path: /etc/nginx/sites-available/{{ website_name | lower }}.conf
  register: site_config

- name: Setup HTML, PHP or MySQL website NGINX Configuration, Hold on...
  template: src={{ website_type | lower }}/basic.conf dest=/etc/nginx/sites-available/{{ website_name | lower }}.conf
  when: site_config.stat.islnk is not defined and (website_type == "html" or website_type == "php" or website_type == "mysql" or website_type == "HTML" or website_type == "PHP" or website_type == "MYSQL")

- name: Setup WordPress website NGINX Configuration, Hold on...
  template: src=wordpress/{{ website_type | lower }}.conf dest=/etc/nginx/sites-available/{{ website_name | lower }}.conf
  when: site_config.stat.islnk is not defined and (website_type == "wp" or website_type == "w3tc" or website_type == "wpfc" or website_type == "WP" or website_type == "W3TC" or website_type == "WPFC")

- name: Enabling {{ website_name | lower }} Website, Hold on...
  file:
    src: /etc/nginx/sites-available/{{ website_name | lower }}.conf
    dest: /etc/nginx/sites-enabled/{{ website_name | lower }}.conf
    state: link
  when: site_config.stat.islnk is not defined
  # The notify will call the ../handlers/main.yml
  notify: service nginx reload

- name: Setup Webroot & Logs Direcroty, Hold on...
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username | lower }}"
    group: "{{ username | lower }}"
  with_items:
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/htdocs
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/ssl
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/conf
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/logs

- name: Setup Symbolic Link for Logs, Hold on...
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username | lower }}"
    group: "{{ username | lower }}"
    force: yes
    state: link
  with_items:
    - { src: "/var/log/nginx/{{ website_name | lower }}.access.log", dest: "/home/{{ username | lower }}/vhosts/{{ website_name | lower }}/logs/access.log" }
    - { src: "/var/log/nginx/{{ website_name | lower }}.error.log", dest: "/home/{{ username | lower }}/vhosts/{{ website_name | lower }}/logs/error.log" }
