---
# Setup Debian Repository

- name: Adding NGINX Repository Key, Hold on...
  apt_key:
    id: B9C9F7DE
    url: http://download.opensuse.org/repositories/home:AnsiPress/{{ ansible_distribution }}_8.0/Release.key
  register: apt_key
  when: ansible_distribution == 'Debian'

- name: Adding NGINX Repository, Hold on...
  apt_repository: repo='deb http://download.opensuse.org/repositories/home:/AnsiPress/{{ ansible_distribution }}_8.0/ /' state=present filename=nginx
  register: repository
  when: ansible_distribution == 'Debian'

- name: Adding PHP Repository Key, Hold on...
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
  register: apt_key
  when: ansible_distribution == 'Debian'

- name: Adding PHP Repository, Hold on...
  apt_repository: repo='deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main' state=present filename=php
  register: repository
  when: ansible_distribution == 'Debian'

- name: Adding MariaDB Repository Key, Hold on...
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  register: apt_key

- name: Adding MariaDB Repository, Hold on...
  apt_repository: repo='deb [arch=amd64,i386,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main' state=present filename=mariadb
  register: repository

- include: roles/libs/tasks/apt/update.yml
  when: repository.changed == True or apt_key.changed == True
