---
- name: Add PHP Repository, Hold on...
  apt_repository: repo=ppa:ondrej/php
  register: php_repo

- include: roles/libs/tasks/apt/update.yml
  when: php_repo.changed == True

- name: Installing PHP, Hold on...
  apt: name={{ item }} state=present
  with_items:
    - php7.1-gd
    - php7.1-cli
    - php7.1-fpm
    - php7.1-curl
    - php7.1-imap
    - php7.1-mysql
    - php7.1-redis
    - php7.1-geoip
    - php7.1-common
    - php7.1-mcrypt
    - php7.1-xdebug
    - php7.1-xmlrpc
    - php7.1-opcache
    - php7.1-memcache
    - php7.1-mbstring
    - php7.1-readline
  register: package_install
  # The notify will call the ../handlers/main.yml
  notify: service php7.1-fpm restart
