---
# We had include service restart module
# Also we have to passs service_name variable which trigger
# service {{ service_name }} restart
- name: service fail2ban restart
  ansible.builtin.service: name=fail2ban state=restarted

- name: service rsyslog restart
  ansible.builtin.service: name=rsyslog state=restarted
